-- Devices of a user's account (the browsers/apps where they are signed in) and
-- the commands one device can send to another (today: switch Modo Vigilancia
-- on or off). Run once, in the Neon SQL editor or with psql.

create table if not exists devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  -- Generated by the browser and kept in its own storage: the same browser is the same device.
  client_id text not null,
  name text not null,
  platform text,
  -- The login session of that browser; removing the device signs it out.
  session_id uuid references sessions(id) on delete set null,
  -- Secret ntfy topic that rings the device's doorbell ("there is a command"); no data travels on it.
  topic text not null,
  -- The device's own switch: may my other devices switch its camera mode on? Off by default.
  remote_enabled boolean not null default false,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, client_id)
);

create index if not exists devices_user_idx on devices (user_id, last_seen_at desc);

create table if not exists device_commands (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references users(id) on delete cascade,
  device_id uuid not null references devices(id) on delete cascade,
  action text not null,
  -- pending | delivered | done | consent | error | expired
  status text not null default 'pending',
  message text,
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists device_commands_device_idx on device_commands (device_id, status, created_at);
